# Site settings
title: Portfolio
email: aeqv226@gmail.com
url: https://github.com/AndresQuinto5/andresquinto5.github.io
description: "BSc Computer Science graduate specializing in Data Science, Analytics, and Web Development. Passionate about turning data into actionable insights and creating innovative web solutions."
keywords: "data science, analytics, web development, computer science, portfolio"
skills: "BSc Computer Science - Data Science | Analytics - Web Developer"
meta_author: Quinto Andres

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Andres Quinto
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/AndresQuinto5
  - title: linkedin
    url: https://www.linkedin.com/in/aeqv226/

# Postal address (add as many lines as necessary)
address:
  - line: Guatemala City
  - line: Guatemala

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
